name: Python Package using Conda

on: [push]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: '3.10'

    - name: Install Miniconda
      uses: conda-incubator/setup-miniconda@v2
      with:
        activate-environment: test-env
        environment-file: environment.yml
        python-version: 3.10
        auto-activate-base: false

    - name: Lint with flake8
      run: |
        conda run -n test-env flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        conda run -n test-env flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

    - name: Test with pytest
      run: |
        conda run -n test-env pytest
